site_name: matrix-help.envs.net
site_description: envs.net | matrix help
repo_name: <i class="fa fa-github" aria-hidden="true"></i> edit on gitea
repo_url: https://git.envs.net/envs/matrix-doc

#theme: cyborg
theme: readthedocs

nav:
- Home: index.md
- Why Matrix?: why.md
- First steps: first-steps.md
- Important settings: settings.md
- Clients / Instalation: clients.md
- Messages: messaging.md
- Rooms: rooms.md
- Notifications: notifications.md
- Communities: communities.md
- Encryption: encryption.md
- Integrations: integrations.md
- FAQ: faq.md
- Development: development.md

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 1
        separator: "_"
