site_name: matrix-help.envs.net
site_description: envs.net | matrix help
repo_name: <i class="fa fa-github" aria-hidden="true"></i> edit on gitea
repo_url: https://git.envs.net/envs/matrix-doc

theme:
    name: material
    palette:
        scheme: slate
        primary: black
        accent: teal
    logo: assets/favicon.ico
    favicon: assets/favicon.ico
    font:
        text: Jetbrains Mono
extra_css:
  - stylesheets/extra.css

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: "#"
        baselevel: 1
        separator: "_"

nav:
    - Home: index.md
    - Why Matrix?: why.md
    - First steps: first-steps.md
    - Important settings: settings.md
    - Clients / Installation:
        - Overview: clients.md
        - Element Web Browser: clients/browser.md
        - Element Desktop: clients/desktop.md
        - Element Mobile: clients/mobile.md
        - Install on Linux: clients/install_linux.md
        - More clients: clients/more_clients.md
    - Messages:
        - Overview: messaging.md
        - Format messages: messaging/formatting.md
        - Messages search: messaging/search.md
    - Rooms:
        - Overview: rooms.md
        - Create rooms: rooms/create.md
        - Find rooms: rooms/find.md
        - Delete rooms: rooms/delete.md
        - Share rooms: rooms/sharing.md
        - Message retention policies: rooms/retention_policies.md
    - Notifications: notifications.md
    - Encryption: encryption.md
    - Advanced:
        - Spaces: advanced/spaces.md
        - Integrations: advanced/integrations.md
        - Abuse Management: advanced/abuse_management.md
        - IRC Bridges: advanced/irc_bridge.md
        - Bot's: advanced/bots.md
    - FAQ: faq.md
    - Impressum: impressum.md
    - Development: development.md
